### PR TITLE
WIP Port to qt5

### PR DESCRIPTION
**Pull request by pierrewillenbrockdfki**
@planthaber This is supposed to land on a branch called "feature/qt5", but github does not allow to specify that in a pull request, so that branch would have to be created beforehand.

### CODE REVIEW

**Comment by planthaber** [comment]
branch created

**Comment by haider8645** [comment]
@pierrewillenbrockdfki Could you please also append the following small changes to your pull request. Thanks!

image

**Comment by pierrewillenbrockdfki** [comment]
@haider8645 both changes already are in the PR?

**Comment by pierrewillenbrockdfki** [comment]
Going to merge this myself once @haider8645 is happy.

**Comment by haider8645** [comment]
@pierrewillenbrockdfki Yes, sorry. I think I just looked at the master. My bad! Im happy :D

**Pull request merged**
